// <auto-generated />
namespace PsReservationPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TableModel_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableModel_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201902210858257_TableModel_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
